version: '3.8'

services:
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    ports:
      - "8080:8080"
    restart: always
    environment:
      ##환경변수
      - SPRING_PROFILES_ACTIVE=prod
    volumes:
      - ./logs:/app/logs