name: Spring App Docker deploy Pipeline

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          ls -la taskapp || echo "taskapp directory not found"
          find . -name gradlew
          if [ -f "taskapp/gradlew" ]; then echo "gradlew found"; else echo "gradlew not found"; fi

      - name: Grant execute permission for gradlew
        run: chmod +x taskapp/gradlew

      - name: Build with Gradle
        working-directory: taskapp
        run: |
          ./gradlew clean build -x test --stacktrace
          ls -la build/libs/ || echo "build/libs directory not found"

      - name: Debug build output
        run: |
          ls -la taskapp || echo "taskapp directory not found"
          ls -la taskapp/build || echo "build directory not found"
          ls -la taskapp/build/libs || echo "libs directory not found"
          find taskapp -name "*.jar"

      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          cp taskapp/build/libs/*.jar deploy/app.jar || echo "No JAR file found in taskapp/build/libs/"
          cp Dockerfile deploy/
          cp docker-compose.yml deploy/
          cat > deploy/deploy.sh << 'EOL'
          #!/bin/bash
          set -e
          docker-compose down || true
          docker-compose up --build -d
          docker-compose logs -f --tail=100
          EOL
          chmod +x deploy/deploy.sh

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: deploy/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: deploy-package

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Transfer files to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'mkdir -p ~/app'
          scp -i ~/.ssh/id_rsa * ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app/

      - name: Deploy on EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            cd ~/app
            chmod +x deploy.sh
            ./deploy.sh
          '