name: Spring App Docker deploy Pipeline

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Grant execute permission for gradlew
        run: chmod +x taskapp/gradlew

      - name: Build with Gradle
        working-directory: taskapp
        run: |
          ./gradlew clean bootJar -x test --stacktrace
          ls -la build/libs || echo "build/libs directory not found"
          find . -name "*.jar"

      - name: Prepare deployment package
        run: |
          mkdir -p deploy
          cp taskapp/build/libs/taskapp-0.0.1-SNAPSHOT.jar deploy/app.jar || echo "No JAR file found in taskapp/build/libs/"
          cp Dockerfile deploy/
          cp docker-compose.yml deploy/
          cat > deploy/deploy.sh << 'EOL'
          #!/bin/bash
          set -e
          docker-compose down || true
          docker-compose up --build -d
          docker-compose logs -f --tail=100
          EOL
          chmod +x deploy/deploy.sh

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: deploy-package
          path: deploy/

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4.1.7
        with:
          name: deploy-package
          path: ./deploy

      - name: Debug environment
        run: |
          pwd
          whoami
          echo "Home directory: $HOME"
          ls -la || echo "ls -la failed"

      - name: Check SSH secrets
        run: |
          if [ -z "${{ secrets.EC2_SSH_KEY }}" ]; then echo "EC2_SSH_KEY is empty"; else echo "EC2_SSH_KEY is set"; fi
          if [ -z "${{ secrets.EC2_HOST }}" ]; then echo "EC2_HOST is empty"; else echo "EC2_HOST is set"; fi
          if [ -z "${{ secrets.EC2_USER }}" ]; then echo "EC2_USER is empty"; else echo "EC2_USER is set"; fi

      - name: Set up SSH key
        run: |
          mkdir -p /home/runner/.ssh || echo "Failed to create /home/runner/.ssh"
          echo "${{ secrets.EC2_SSH_KEY }}" > /home/runner/.ssh/id_rsa || echo "Failed to write SSH key"
          chmod 600 /home/runner/.ssh/id_rsa || echo "Failed to set permissions on id_rsa"
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> /home/runner/.ssh/known_hosts || echo "Failed to update known_hosts"

      - name: Transfer files to EC2
        run: |
          ssh -i /home/runner/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'mkdir -p ~/app' || echo "Failed to create remote app directory"
          scp -i /home/runner/.ssh/id_rsa deploy/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app/ || echo "Failed to transfer files to EC2"

      - name: Deploy on EC2
        run: |
          ssh -i /home/runner/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            cd ~/app
            chmod +x deploy.sh
            ./deploy.sh
          ' || echo "Failed to deploy on EC2"